version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn coverage
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn -v
workflows:
  version: 2
  build_if_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^test.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^test.*/
            branches:
              ignore: /.*/
